### ISSUE TITLE
Template path handling

### ISSUE THREAD

**Issue by WolfgangFahl** [tholzheim/wikirender#1]
see
    https://stackoverflow.com/questions/21765692/flask-render-template-with-path
    https://stackoverflow.com/questions/37968787/jinja2-load-templates-from-separate-location-than-working-directory
        https://stackoverflow.com/a/39717092/1497139
    https://stackoverflow.com/questions/23327293/flask-raises-templatenotfound-error-even-though-template-file-exists

**Comment by WolfgangFahl** [comment]
see https://github.com/pallets/jinja/issues/1365

**Comment by tholzheim** [comment]
The ChoiceLoader hopefully fixes the issue by allowing to load multiple template environments
https://github.com/tholzheim/wikirender/blob/6f28c50ced7ab493f2c0845ff4975631614b79f2/wikifile/wikiRender.py#L109
