### ISSUE TITLE
Renaming WikiFix to WikiCorpus

### ISSUE THREAD

**Issue by tholzheim** [tholzheim/wikirender#6]
Since WikiFix provides methods to update wikipages and extract content from wikipages a better name for the class would be WikiCorpus.
WikiCorpus would then consist of WikiFile objects representing the wikipages in the actual wiki.
Meaning that we get a interface to  wiki based on the file content.
Furthermore, page generation functionalities for WikiCorpus and WikiFile could be added.
e.g. Import  data by generating a page using the given template and data

> It should be noted that WikiFile only provides access to the raw file content. Properties and further elements of the page that are generated through templates or queries can therefore not be accessed through this method.

**Comment by WolfgangFahl** [comment]
I find it interesting that the postfix "Corpus" is getting so popular. It is a new postfix in the list of possible ones for implementing a 
![grafik](https://user-images.githubusercontent.com/1336221/121631618-b74f0a80-ca7f-11eb-96bb-1e5e38d7cb42.png) a "filebox" of things where you have things of a certain type and a container for these things:


- List
- Table
- Manager
- Repository
- Container
- ...

**Comment by tholzheim** [comment]
Yeah you are right, maybe **WikiFileManager** is a better name for it.

**Comment by tholzheim** [comment]
See 23e4b481314a5b70263fafdd250d793c0ffa94dd
